// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpjMOOLCTAp0Dr5JnbQuMqLKVX9KEF5zU',
    appId: '1:315496642953:web:d40d38ed447851c4ab4958',
    messagingSenderId: '315496642953',
    projectId: 'pofeservices-30748',
    authDomain: 'pofeservices-30748.firebaseapp.com',
    storageBucket: 'pofeservices-30748.firebasestorage.app',
    measurementId: 'G-QDLPRLDG2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoU8nQ1aG9eSRlN8D1ZsKjXaucK6_si6k',
    appId: '1:315496642953:android:ac8e6ebf7d1a8554ab4958',
    messagingSenderId: '315496642953',
    projectId: 'pofeservices-30748',
    storageBucket: 'pofeservices-30748.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpjMOOLCTAp0Dr5JnbQuMqLKVX9KEF5zU',
    appId: '1:315496642953:web:82632065d780dd67ab4958',
    messagingSenderId: '315496642953',
    projectId: 'pofeservices-30748',
    authDomain: 'pofeservices-30748.firebaseapp.com',
    storageBucket: 'pofeservices-30748.firebasestorage.app',
    measurementId: 'G-BBKVZQCM2J',
  );
}
